package vistas;

import Controladores.ControladorBalanzaC;
import Vistas.VistaBalanzaComprobacion;
import utilidades.Fondo;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class Dashboard extends javax.swing.JFrame {
    boolean visible = false;
    Color colorDefaultModulo,
            colorActivoModulo,
            colorDefaultOp,
            colorActivoOp,
            colorMenuLateral,
            colorFuente,
            colorFuente2;

    public Dashboard() {
        initComponents();
        setImageLabel(logo, "src/img/logo.png");
        setImageLabel(home, "src/img/cargando.gif");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        color();
        config();
        ocultarMod(0);
        panels();

    }

    public void iniciar() {
        this.setVisible(true);
    }

    //Método para colocar el tamaño ""X""
    public void setImageLabel(JLabel log, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(log.getWidth(), log.getHeight(), Image.SCALE_DEFAULT));
        log.setIcon(icon);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        menuLateral = new javax.swing.JPanel();
        opHome = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        panelOp1 = new javax.swing.JPanel();
        menu1Op1 = new javax.swing.JLabel();
        menu1Op2 = new javax.swing.JLabel();
        panelOp2 = new javax.swing.JPanel();
        menu2Op1 = new javax.swing.JLabel();
        menu2Op2 = new javax.swing.JLabel();
        panelOp3 = new javax.swing.JPanel();
        menu3Op1 = new javax.swing.JLabel();
        menu3Op2 = new javax.swing.JLabel();
        menu3Op3 = new javax.swing.JLabel();
        panelOp4 = new javax.swing.JPanel();
        menu4Op1 = new javax.swing.JLabel();
        menu4Op2 = new javax.swing.JLabel();
        panelOp5 = new javax.swing.JPanel();
        menu5Op1 = new javax.swing.JLabel();
        panelOp6 = new javax.swing.JPanel();
        menu6Op1 = new javax.swing.JLabel();
        lbSistemasContables = new javax.swing.JLabel();
        opMenu1Catalogo = new javax.swing.JLabel();
        opMenu2LibroDiario = new javax.swing.JLabel();
        opMenu3Reportes = new javax.swing.JLabel();
        opMenu4Cierre = new javax.swing.JLabel();
        opMenu5AcercaDe = new javax.swing.JLabel();
        opMenu6 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        panelTop = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        panelCopyR = new javax.swing.JPanel();
        lbCopyR = new javax.swing.JLabel();
        rSLabelHora1 = new rojeru_san.RSLabelHora();
        rSLabelFecha1 = new rojeru_san.RSLabelFecha();
        jLabel3 = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        opSalir = new javax.swing.JLabel();
        lbBienvenida = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistemas Contables");
        setUndecorated(true);

        menuLateral.setForeground(new java.awt.Color(255, 255, 255));

        opHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opHomeMousePressed(evt);
            }
        });

        home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home.setForeground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout opHomeLayout = new javax.swing.GroupLayout(opHome);
        opHome.setLayout(opHomeLayout);
        opHomeLayout.setHorizontalGroup(
            opHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opHomeLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        opHomeLayout.setVerticalGroup(
            opHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opHomeLayout.createSequentialGroup()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelOp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp1MousePressed(evt);
            }
        });

        menu1Op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu1Op1.setForeground(new java.awt.Color(255, 255, 255));
        menu1Op1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu1Op1.setText("Ingresar Catalogo");
        menu1Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu1Op1.setOpaque(true);
        menu1Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu1Op1MousePressed(evt);
            }
        });

        menu1Op2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu1Op2.setForeground(new java.awt.Color(255, 255, 255));
        menu1Op2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu1Op2.setText("Ver Catalogo");
        menu1Op2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu1Op2.setOpaque(true);
        menu1Op2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu1Op2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp1Layout = new javax.swing.GroupLayout(panelOp1);
        panelOp1.setLayout(panelOp1Layout);
        panelOp1Layout.setHorizontalGroup(
            panelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu1Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu1Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelOp1Layout.setVerticalGroup(
            panelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu1Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu1Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp2MousePressed(evt);
            }
        });

        menu2Op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu2Op1.setForeground(new java.awt.Color(255, 255, 255));
        menu2Op1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu2Op1.setText("Ingresar Libro Diario");
        menu2Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu2Op1.setOpaque(true);
        menu2Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu2Op1MousePressed(evt);
            }
        });

        menu2Op2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu2Op2.setForeground(new java.awt.Color(255, 255, 255));
        menu2Op2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu2Op2.setText("Ver Libro Diario");
        menu2Op2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu2Op2.setOpaque(true);
        menu2Op2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu2Op2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp2Layout = new javax.swing.GroupLayout(panelOp2);
        panelOp2.setLayout(panelOp2Layout);
        panelOp2Layout.setHorizontalGroup(
            panelOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menu2Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu2Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelOp2Layout.setVerticalGroup(
            panelOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu2Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu2Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp3MousePressed(evt);
            }
        });

        menu3Op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu3Op1.setForeground(new java.awt.Color(255, 255, 255));
        menu3Op1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu3Op1.setText("Report1");
        menu3Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu3Op1.setOpaque(true);
        menu3Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu3Op1MousePressed(evt);
            }
        });

        menu3Op2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu3Op2.setForeground(new java.awt.Color(255, 255, 255));
        menu3Op2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu3Op2.setText("Report2");
        menu3Op2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu3Op2.setOpaque(true);
        menu3Op2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu3Op2MousePressed(evt);
            }
        });

        menu3Op3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu3Op3.setForeground(new java.awt.Color(255, 255, 255));
        menu3Op3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu3Op3.setText("Report3");
        menu3Op3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu3Op3.setOpaque(true);
        menu3Op3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu3Op3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp3Layout = new javax.swing.GroupLayout(panelOp3);
        panelOp3.setLayout(panelOp3Layout);
        panelOp3Layout.setHorizontalGroup(
            panelOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu3Op1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu3Op2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu3Op3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelOp3Layout.setVerticalGroup(
            panelOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu3Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu3Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu3Op3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp4MousePressed(evt);
            }
        });

        menu4Op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu4Op1.setForeground(new java.awt.Color(255, 255, 255));
        menu4Op1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu4Op1.setText("Ver");
        menu4Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu4Op1.setOpaque(true);
        menu4Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu4Op1MousePressed(evt);
            }
        });

        menu4Op2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu4Op2.setForeground(new java.awt.Color(255, 255, 255));
        menu4Op2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu4Op2.setText("Opc");
        menu4Op2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu4Op2.setOpaque(true);
        menu4Op2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu4Op2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp4Layout = new javax.swing.GroupLayout(panelOp4);
        panelOp4.setLayout(panelOp4Layout);
        panelOp4Layout.setHorizontalGroup(
            panelOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu4Op2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(menu4Op1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelOp4Layout.setVerticalGroup(
            panelOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu4Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu4Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelOp5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp5MousePressed(evt);
            }
        });

        menu5Op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu5Op1.setForeground(new java.awt.Color(255, 255, 255));
        menu5Op1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu5Op1.setText("Ver");
        menu5Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu5Op1.setOpaque(true);
        menu5Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu5Op1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp5Layout = new javax.swing.GroupLayout(panelOp5);
        panelOp5.setLayout(panelOp5Layout);
        panelOp5Layout.setHorizontalGroup(
            panelOp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(menu5Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelOp5Layout.setVerticalGroup(
            panelOp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu5Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOp6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp6MousePressed(evt);
            }
        });

        menu6Op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu6Op1.setForeground(new java.awt.Color(255, 255, 255));
        menu6Op1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu6Op1.setText("Ver");
        menu6Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu6Op1.setOpaque(true);
        menu6Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu6Op1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp6Layout = new javax.swing.GroupLayout(panelOp6);
        panelOp6.setLayout(panelOp6Layout);
        panelOp6Layout.setHorizontalGroup(
            panelOp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(menu6Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelOp6Layout.setVerticalGroup(
            panelOp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu6Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbSistemasContables.setBackground(new java.awt.Color(204, 204, 204));
        lbSistemasContables.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSistemasContables.setForeground(new java.awt.Color(255, 255, 255));
        lbSistemasContables.setText(".");

        opMenu1Catalogo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu1Catalogo.setForeground(new java.awt.Color(0, 51, 153));
        opMenu1Catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu1Catalogo.setText("Catalogo");
        opMenu1Catalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opMenu1Catalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu1CatalogoMousePressed(evt);
            }
        });

        opMenu2LibroDiario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu2LibroDiario.setForeground(new java.awt.Color(0, 51, 153));
        opMenu2LibroDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu2LibroDiario.setText("Libro Diario");
        opMenu2LibroDiario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opMenu2LibroDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu2LibroDiarioMousePressed(evt);
            }
        });

        opMenu3Reportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu3Reportes.setForeground(new java.awt.Color(0, 51, 153));
        opMenu3Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu3Reportes.setText("Reportes");
        opMenu3Reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opMenu3Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu3ReportesMousePressed(evt);
            }
        });

        opMenu4Cierre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu4Cierre.setForeground(new java.awt.Color(0, 51, 153));
        opMenu4Cierre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu4Cierre.setText("Cierre");
        opMenu4Cierre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opMenu4Cierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu4CierreMousePressed(evt);
            }
        });

        opMenu5AcercaDe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu5AcercaDe.setForeground(new java.awt.Color(0, 51, 153));
        opMenu5AcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu5AcercaDe.setText("Acerca de");
        opMenu5AcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opMenu5AcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu5AcercaDeMousePressed(evt);
            }
        });

        opMenu6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu6.setForeground(new java.awt.Color(0, 51, 153));
        opMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu6.setText("Opción");
        opMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout menuLateralLayout = new javax.swing.GroupLayout(menuLateral);
        menuLateral.setLayout(menuLateralLayout);
        menuLateralLayout.setHorizontalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opMenu3Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opMenu4Cierre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opMenu5AcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(panelOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addContainerGap(5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(opMenu2LibroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLateralLayout.createSequentialGroup()
                        .addComponent(lbSistemasContables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(188, 188, 188))
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opMenu1Catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        menuLateralLayout.setVerticalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbSistemasContables)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(opMenu1Catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opMenu2LibroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opMenu3Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opMenu4Cierre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opMenu5AcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelCopyR.setBackground(new java.awt.Color(255, 255, 255));

        lbCopyR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCopyR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCopyR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelCopyRLayout = new javax.swing.GroupLayout(panelCopyR);
        panelCopyR.setLayout(panelCopyRLayout);
        panelCopyRLayout.setHorizontalGroup(
            panelCopyRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCopyRLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbCopyR, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        panelCopyRLayout.setVerticalGroup(
            panelCopyRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCopyRLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbCopyR, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSLabelHora1.setForeground(new java.awt.Color(153, 0, 0));
        rSLabelHora1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N

        rSLabelFecha1.setForeground(new java.awt.Color(153, 0, 0));
        rSLabelFecha1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCopyR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rSLabelFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addComponent(escritorio))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(escritorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCopyR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        opSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opSalir.setForeground(new java.awt.Color(153, 0, 0));
        opSalir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        opSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        opSalir.setText("Salir");
        opSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opSalirMousePressed(evt);
            }
        });

        lbBienvenida.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalirLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(lbBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(153, 153, 153)
                .addComponent(opSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalirLayout.createSequentialGroup()
                .addComponent(lbBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(opSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addComponent(panelSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSalir.getAccessibleContext().setAccessibleParent(opHome);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelOp1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp1MousePressed
        colorDefault();
        panelOp1.setBackground(colorActivoModulo);
    }//GEN-LAST:event_panelOp1MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        ocultarMod(0);
        visible = !visible;
        menuLateral.setVisible(visible);
    }//GEN-LAST:event_jLabel3MousePressed

    private void opSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opSalirMousePressed
        colorDefault();

        opDefault();
//        panelSalir.setBackground(colorActivoModulo);
        VistaSalir vista = new VistaSalir("Saliendo");
        vista.setVisible(true);


    }//GEN-LAST:event_opSalirMousePressed

    private void opMenu3ReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu3ReportesMousePressed
        colorDefault();
        opDefault();
        ocultarMod(2);
    }//GEN-LAST:event_opMenu3ReportesMousePressed

    private void menu1Op1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1Op1MousePressed
        opDefault();
        menu1Op1.setBackground(colorActivoOp);
//       VistaConsultar consultarAutor= new VistaConsultar(new JFrame(), true, "Autores");
////       modificado kevin
//       ControladorConsultarAutor ctlConsultarAutor= new  ControladorConsultarAutor(consultarAutor);
//        consultarAutor.iniciar();
    }//GEN-LAST:event_menu1Op1MousePressed

    private void opMenu5AcercaDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu5AcercaDeMousePressed
        colorDefault();
        opDefault();
        ocultarMod(4);
    }//GEN-LAST:event_opMenu5AcercaDeMousePressed

    private void menu3Op1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3Op1MousePressed
        opDefault();
        menu3Op1.setBackground(colorActivoOp);
        VistaBalanzaComprobacion vista = new VistaBalanzaComprobacion(new JFrame(), true);
       ControladorBalanzaC crt = new ControladorBalanzaC(vista);
       vista.setVisible(true);

    }//GEN-LAST:event_menu3Op1MousePressed

    private void panelOp3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelOp3MousePressed

    private void menu3Op2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3Op2MousePressed
        opDefault();
        menu3Op2.setBackground(colorActivoOp);
    }//GEN-LAST:event_menu3Op2MousePressed

    private void menu3Op3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3Op3MousePressed
        opDefault();
        menu3Op3.setBackground(colorActivoOp);
        //    ControladorEvaluarExpresion ctlEvaluarExpresion = new ControladorEvaluarExpresion(vista);

    }//GEN-LAST:event_menu3Op3MousePressed

    private void opMenu4CierreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu4CierreMousePressed
        colorDefault();
        opDefault();
        ocultarMod(3);
    }//GEN-LAST:event_opMenu4CierreMousePressed

    private void menu4Op1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu4Op1MousePressed
        opDefault();
        menu4Op1.setBackground(colorActivoOp);
//        VistaConsultar formConsultar = new VistaConsultar(new JFrame(), true, "Consulta Participante");
//        ControladorParticipante ctlparticipante = new ControladorParticipante(formConsultar,userActivo);
//        formConsultar.setVisible(true);
    }//GEN-LAST:event_menu4Op1MousePressed

    private void menu4Op2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu4Op2MousePressed
        opDefault();
        menu4Op2.setBackground(colorActivoOp);

    }//GEN-LAST:event_menu4Op2MousePressed

    private void panelOp4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelOp4MousePressed

    private void opMenu1CatalogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu1CatalogoMousePressed
        opDefault();
        menu1Op1.setBackground(colorActivoOp);
        menu1Op2.setBackground(colorActivoOp);
        colorDefault();
        opDefault();
        ocultarMod(1);

    }//GEN-LAST:event_opMenu1CatalogoMousePressed

    private void menu5Op1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu5Op1MousePressed
        opDefault();
        menu5Op1.setBackground(colorActivoOp);
//        VistaConsultar formConsultar = new VistaConsultar(new JFrame(), true, "Consulta Usuario");
//        ControladorUsuario ctlUsuarios = new ControladorUsuario(formConsultar,userActivo);
//        formConsultar.iniciar();
    }//GEN-LAST:event_menu5Op1MousePressed

    private void panelOp5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelOp5MousePressed

    private void menu6Op1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu6Op1MousePressed
        opDefault();
        menu6Op1.setBackground(colorActivoOp);
//        VistaConsultaRol frmConsultRol = new VistaConsultaRol(new JFrame(), true, "Consulta Rol");
//        ControladorRol ctrRol = new ControladorRol(frmConsultRol,userActivo);
//        frmConsultRol.setVisible(true);
    }//GEN-LAST:event_menu6Op1MousePressed

    private void panelOp6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelOp6MousePressed

    private void opMenu6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu6MousePressed
        colorDefault();
        opDefault();
        ocultarMod(5);
    }//GEN-LAST:event_opMenu6MousePressed

    private void opMenu2LibroDiarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu2LibroDiarioMousePressed
        colorDefault();
        opDefault();
        ocultarMod(6);
    }//GEN-LAST:event_opMenu2LibroDiarioMousePressed

    private void menu2Op1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2Op1MousePressed
        opDefault();
        menu2Op2.setBackground(colorActivoOp);
    }//GEN-LAST:event_menu2Op1MousePressed

    private void panelOp2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelOp2MousePressed

    private void menu1Op2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1Op2MousePressed
        opDefault();
        menu1Op2.setBackground(colorActivoOp);
//         VistaConsultarCursoAsignado formConsultar =
//                new VistaConsultarCursoAsignado(new JFrame(), true, "Cursos Asignados");
//        ControladorCursosAsignados ctlCursosAsignados = new ControladorCursosAsignados(formConsultar,userActivo);
//          formConsultar.setVisible(true);
    }//GEN-LAST:event_menu1Op2MousePressed

    private void menu2Op2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2Op2MousePressed
        opDefault();
        menu2Op1.setBackground(colorActivoOp);
    }//GEN-LAST:event_menu2Op2MousePressed

    private void opHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opHomeMousePressed

    }//GEN-LAST:event_opHomeMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel home;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbBienvenida;
    private javax.swing.JLabel lbCopyR;
    private javax.swing.JLabel lbSistemasContables;
    private javax.swing.JLabel logo;
    public javax.swing.JLabel menu1Op1;
    public javax.swing.JLabel menu1Op2;
    private javax.swing.JLabel menu2Op1;
    private javax.swing.JLabel menu2Op2;
    private javax.swing.JLabel menu3Op1;
    private javax.swing.JLabel menu3Op2;
    private javax.swing.JLabel menu3Op3;
    private javax.swing.JLabel menu4Op1;
    private javax.swing.JLabel menu4Op2;
    private javax.swing.JLabel menu5Op1;
    private javax.swing.JLabel menu6Op1;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JPanel opHome;
    public javax.swing.JLabel opMenu1Catalogo;
    public javax.swing.JLabel opMenu2LibroDiario;
    public javax.swing.JLabel opMenu3Reportes;
    public javax.swing.JLabel opMenu4Cierre;
    public javax.swing.JLabel opMenu5AcercaDe;
    public javax.swing.JLabel opMenu6;
    private javax.swing.JLabel opSalir;
    private javax.swing.JPanel panelCopyR;
    public javax.swing.JPanel panelOp1;
    public javax.swing.JPanel panelOp2;
    public javax.swing.JPanel panelOp3;
    public javax.swing.JPanel panelOp4;
    public javax.swing.JPanel panelOp5;
    public javax.swing.JPanel panelOp6;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JPanel panelTop;
    private rojeru_san.RSLabelFecha rSLabelFecha1;
    private rojeru_san.RSLabelHora rSLabelHora1;
    // End of variables declaration//GEN-END:variables
 public void colorDefault() {
        menuLateral.setBackground(colorMenuLateral);
        menuLateral.setForeground(colorFuente);

        opHome.setBackground(colorDefaultModulo);
        home.setForeground(colorFuente2);

        panelOp1.setBackground(colorDefaultModulo);
        opMenu1Catalogo.setForeground(colorFuente2);

        panelOp3.setBackground(colorDefaultModulo);
        opMenu3Reportes.setForeground(colorFuente2);

        panelOp4.setBackground(colorDefaultModulo);
        opMenu4Cierre.setForeground(colorFuente2);

        panelOp5.setBackground(colorDefaultModulo);
        opMenu5AcercaDe.setForeground(colorFuente2);

        panelOp6.setBackground(colorDefaultModulo);
        opMenu6.setForeground(colorFuente2);

        panelOp2.setBackground(colorDefaultModulo);
        opMenu2LibroDiario.setForeground(colorFuente2);

        panelSalir.setBackground(colorMenuLateral);

        opSalir.setForeground(colorFuente2);

        panelTop.setBackground(colorMenuLateral);

    }

    public void opDefault() {
        opHome.setBackground(colorMenuLateral);
        opSalir.setBackground(colorMenuLateral);
        panelCopyR.setBackground(colorMenuLateral);
        //opciones
        menu1Op1.setBackground(colorDefaultOp);
        menu1Op2.setBackground(colorDefaultOp);
        menu2Op1.setBackground(colorDefaultOp);
        menu2Op2.setBackground(colorDefaultOp);
        menu3Op1.setBackground(colorDefaultOp);
        menu3Op2.setBackground(colorDefaultOp);
        menu3Op3.setBackground(colorDefaultOp);
        menu4Op1.setBackground(colorDefaultOp);
        menu4Op2.setBackground(colorDefaultOp);
        menu5Op1.setBackground(colorDefaultOp);
        menu6Op1.setBackground(colorDefaultOp);

    }

    public void color() {
        colorDefaultModulo = new Color(153, 0, 0);
        colorActivoModulo = new Color(102, 0, 0);
        colorDefaultOp = new Color(153, 0, 0);
        colorActivoOp = new Color(102, 0, 0);
        colorMenuLateral = new Color(153, 0, 0); //COLOR DE TODO EL PANEL
        colorFuente = new Color(255, 255, 255);
        colorFuente2 = new Color(255, 255, 255);
    }

    public void ocultarMod(int valor) {
        switch (valor) {
            case 0 -> {
                this.panelOp1.setVisible(false);
                this.panelOp3.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp6.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 1 -> {
                panelOp1.setBackground(colorActivoModulo);
                panelOp1.setVisible(!panelOp1.isVisible());
                this.panelOp3.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp6.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 2 -> {
                panelOp3.setBackground(colorActivoModulo);
                panelOp3.setVisible(!panelOp3.isVisible());
                this.panelOp1.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp6.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 3 -> {
                panelOp4.setBackground(colorActivoModulo);
                panelOp4.setVisible(!panelOp4.isVisible());
                this.panelOp1.setVisible(false);
                this.panelOp3.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp6.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 4 -> {
                panelOp5.setBackground(colorActivoModulo);
                panelOp5.setVisible(!panelOp5.isVisible());
                this.panelOp1.setVisible(false);
                this.panelOp3.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp6.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 5 -> {
                panelOp6.setBackground(colorActivoModulo);
                panelOp6.setVisible(!panelOp6.isVisible());
                this.panelOp1.setVisible(false);
                this.panelOp3.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 6 -> {
                panelOp2.setBackground(colorActivoModulo);
                panelOp2.setVisible(!panelOp2.isVisible());
                this.panelOp1.setVisible(false);
                this.panelOp3.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp6.setVisible(false);
                break;
            }

        }

    }

    public void copyright() {

        this.lbCopyR.setMaximumSize(panelCopyR.getMaximumSize());
        this.lbCopyR.setForeground(colorFuente2);
        this.lbCopyR.setText("Sistemas Contables © UES 2024");
    }

    public void config() {
        colorDefault();
        opDefault();
        copyright();
        menuLateral.setVisible(visible);
        opHome.setVisible(true);
        opSalir.setVisible(true);
        this.escritorio.setBorder(new Fondo("/img/fondo.jpg"));
        lbSistemasContables.setText("Sistemas Contables");
        lbBienvenida.setText("Bienvenido al Sistema");
        lbBienvenida.setForeground(colorFuente2);

    }

    public void panels() {
        panelOp1.setVisible(false);
        panelOp3.setVisible(false);
        panelOp4.setVisible(false);
        panelOp5.setVisible(false);
        panelOp6.setVisible(false);
        panelOp2.setVisible(false);

    }
}
