package Vistas;

import vistas.Dashboard;

public class LibroDiario extends javax.swing.JDialog {

    public LibroDiario(java.awt.Frame parent, boolean modal,
            String titulo) {
        super(parent, modal);
        initComponents();
        lbTitulo.setText(titulo);
        this.setLocation(420, 200);
        
    }

    public void iniciar() {
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSCalendar1 = new rojeru_san.componentes.RSCalendar();
        materialTextField1 = new principal.MaterialTextField();
        rSCalendar2 = new rojeru_san.componentes.RSCalendar();
        materialTextField2 = new principal.MaterialTextField();
        panelFondo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbFecha = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDatos = new rojerusan.RSTableMetro();
        tfFecha = new newscomponents.RSDateChooser();
        lbTitulo1 = new javax.swing.JLabel();
        lbCodigoCuenta = new javax.swing.JLabel();
        cbDebeHaber = new RSMaterialComponent.RSComboBoxMaterial();
        lbTransaccion = new javax.swing.JLabel();
        lbNombreCuenta = new javax.swing.JLabel();
        lbConcepto = new javax.swing.JLabel();
        lbPartidaAnterior = new javax.swing.JLabel();
        lbMonto = new javax.swing.JLabel();
        lbPartidaIngresar = new javax.swing.JLabel();
        tfMonto = new principal.MaterialTextField();
        tfPartidaAnterior = new principal.MaterialTextField();
        tfPartidaIngresar = new principal.MaterialTextField();
        tfNombreCuenta = new principal.MaterialTextField();
        tfConcepto = new principal.MaterialTextField();
        cbCodigo = new RSMaterialComponent.RSComboBoxMaterial();
        btnCerrar = new RSMaterialComponent.RSButtonMaterialTwo();

        materialTextField1.setText("materialTextField1");

        materialTextField2.setText("materialTextField2");

        setLocation(new java.awt.Point(400, 500));
        setUndecorated(true);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 945, 10));
        panelFondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 945, 10));

        lbFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbFecha.setText("Fecha");
        panelFondo.add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 200, 30));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(153, 0, 0));
        panelFondo.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        btnAgregar.setBackground(new java.awt.Color(0, 166, 90));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mas.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelFondo.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, 35));

        btnQuitar.setBackground(new java.awt.Color(255, 102, 102));
        btnQuitar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuitar.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menos.png"))); // NOI18N
        btnQuitar.setText("Quitar");
        btnQuitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuitar.setEnabled(false);
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });
        panelFondo.add(btnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 110, 35));

        btnModificar.setBackground(new java.awt.Color(255, 153, 51));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapiz.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelFondo.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, 35));

        btnGuardar.setBackground(new java.awt.Color(153, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mas.png"))); // NOI18N
        btnGuardar.setText("Guardar Partida");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelFondo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, -1, 40));

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDatos.setColorBackgoundHead(new java.awt.Color(153, 0, 0));
        tbDatos.setColorFilasForeground1(new java.awt.Color(153, 0, 0));
        tbDatos.setColorFilasForeground2(new java.awt.Color(153, 0, 0));
        tbDatos.setColorSelBackgound(new java.awt.Color(153, 0, 0));
        tbDatos.setRowHeight(25);
        jScrollPane2.setViewportView(tbDatos);

        panelFondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 880, 230));

        tfFecha.setBackground(new java.awt.Color(153, 0, 0));
        tfFecha.setBgColor(new java.awt.Color(153, 0, 0));
        tfFecha.setFormatDate("dd/MM/yyyy");
        panelFondo.add(tfFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 200, 40));

        lbTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTitulo1.setForeground(new java.awt.Color(153, 0, 0));
        lbTitulo1.setText("Ingreso de Partidas");
        panelFondo.add(lbTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 220, 40));

        lbCodigoCuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCodigoCuenta.setText("Código de Cuenta");
        panelFondo.add(lbCodigoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 180, 30));

        cbDebeHaber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Parcial", "Debe ", "Haber" }));
        cbDebeHaber.setColorMaterial(new java.awt.Color(153, 0, 0));
        panelFondo.add(cbDebeHaber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 140, -1));

        lbTransaccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTransaccion.setText("Transacción");
        panelFondo.add(lbTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, 30));

        lbNombreCuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNombreCuenta.setText("Nombre de la Cuenta");
        panelFondo.add(lbNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 280, 30));

        lbConcepto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbConcepto.setText("Concepto");
        panelFondo.add(lbConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 80, 30));

        lbPartidaAnterior.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPartidaAnterior.setText("Partida Anterior");
        panelFondo.add(lbPartidaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 130, 30));

        lbMonto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbMonto.setText("Monto $");
        panelFondo.add(lbMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 30));

        lbPartidaIngresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPartidaIngresar.setText("N° de Partida");
        panelFondo.add(lbPartidaIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, 30));

        tfMonto.setForeground(new java.awt.Color(102, 102, 102));
        tfMonto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMontoKeyReleased(evt);
            }
        });
        panelFondo.add(tfMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 30));

        tfPartidaAnterior.setEditable(false);
        tfPartidaAnterior.setBackground(new java.awt.Color(255, 255, 255));
        tfPartidaAnterior.setForeground(new java.awt.Color(102, 102, 102));
        tfPartidaAnterior.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfPartidaAnterior.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPartidaAnteriorKeyReleased(evt);
            }
        });
        panelFondo.add(tfPartidaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 80, 30));

        tfPartidaIngresar.setEditable(false);
        tfPartidaIngresar.setBackground(new java.awt.Color(255, 255, 255));
        tfPartidaIngresar.setForeground(new java.awt.Color(102, 102, 102));
        tfPartidaIngresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfPartidaIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPartidaIngresarKeyReleased(evt);
            }
        });
        panelFondo.add(tfPartidaIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 80, 30));

        tfNombreCuenta.setForeground(new java.awt.Color(102, 102, 102));
        tfNombreCuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNombreCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNombreCuentaKeyReleased(evt);
            }
        });
        panelFondo.add(tfNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 310, 30));

        tfConcepto.setForeground(new java.awt.Color(102, 102, 102));
        tfConcepto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfConcepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfConceptoKeyReleased(evt);
            }
        });
        panelFondo.add(tfConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 410, 30));

        cbCodigo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "11", "111", "" }));
        cbCodigo.setColorMaterial(new java.awt.Color(153, 0, 0));
        panelFondo.add(cbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 180, -1));

        btnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrar.setBorder(null);
        btnCerrar.setText("X");
        btnCerrar.setAlignmentY(0.0F);
        btnCerrar.setBackgroundHover(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnCerrar.setForegroundHover(new java.awt.Color(255, 0, 0));
        btnCerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCerrar.setPadding(0);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        panelFondo.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDatosMouseClicked

        if (tbDatos.getValueAt(0, 0) != null) {
            btnModificar.setEnabled(true);
            btnQuitar.setEnabled(true);
        }
    }//GEN-LAST:event_tbDatosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void tfPartidaAnteriorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPartidaAnteriorKeyReleased
        tfPartidaAnterior.setText(tfPartidaAnterior.getText().toUpperCase());
    }//GEN-LAST:event_tfPartidaAnteriorKeyReleased

    private void tfMontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMontoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMontoKeyReleased

    private void tfPartidaIngresarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPartidaIngresarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPartidaIngresarKeyReleased

    private void tfNombreCuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreCuentaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreCuentaKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
         this.dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void tfConceptoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfConceptoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfConceptoKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ModalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ModalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ModalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ModalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ModalEmpleado dialog = new ModalEmpleado(new javax.swing.JFrame(), true,null);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    private RSMaterialComponent.RSButtonMaterialTwo btnCerrar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnQuitar;
    private RSMaterialComponent.RSComboBoxMaterial cbCodigo;
    private RSMaterialComponent.RSComboBoxMaterial cbDebeHaber;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbCodigoCuenta;
    private javax.swing.JLabel lbConcepto;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbMonto;
    private javax.swing.JLabel lbNombreCuenta;
    private javax.swing.JLabel lbPartidaAnterior;
    private javax.swing.JLabel lbPartidaIngresar;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JLabel lbTransaccion;
    private principal.MaterialTextField materialTextField1;
    private principal.MaterialTextField materialTextField2;
    private javax.swing.JPanel panelFondo;
    private rojeru_san.componentes.RSCalendar rSCalendar1;
    private rojeru_san.componentes.RSCalendar rSCalendar2;
    public rojerusan.RSTableMetro tbDatos;
    public principal.MaterialTextField tfConcepto;
    private newscomponents.RSDateChooser tfFecha;
    public principal.MaterialTextField tfMonto;
    public principal.MaterialTextField tfNombreCuenta;
    public principal.MaterialTextField tfPartidaAnterior;
    public principal.MaterialTextField tfPartidaIngresar;
    // End of variables declaration//GEN-END:variables
}
