/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author guill
 */
public class VistaEstadoResultado extends javax.swing.JDialog {

    /**
     * Creates new form VistaEstadoResultado
     */
    public VistaEstadoResultado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void iniciar() {
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        ventasNetas = new javax.swing.JLabel();
        costoVendido = new javax.swing.JLabel();
        utilidadBruta = new javax.swing.JLabel();
        gastosAdmin = new javax.swing.JLabel();
        gastoVentas = new javax.swing.JLabel();
        utilidadOperacion = new javax.swing.JLabel();
        ingresosFinancieros = new javax.swing.JLabel();
        gastosFinancieros = new javax.swing.JLabel();
        utilidadAntes = new javax.swing.JLabel();
        isr = new javax.swing.JLabel();
        reservaLegal = new javax.swing.JLabel();
        utilidadEjercicio = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        inventariofinal = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        generar = new javax.swing.JButton();
        reporte = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        jLabel19.setText("jLabel17");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("jLabel17");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 235, 235));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ESTADO DE RESULTADO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ELIJA LAS FECHAS DE DONDE A DONDE DESEA VER EL ESTADO DE RESULTADO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 70, 980, 27));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, 970, 20));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("VENTAS NETAS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 231, 343, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 970, 12));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("COSTO DE LO VENDIDO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 263, 343, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("UTILIDAD BRUTA:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 295, 343, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("GASTOS ADMINISTRATIVOS:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 327, 343, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("GASTOS DE VENTAS:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 359, 343, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("UTILIDAD DE OPERACION:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 391, 343, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("INGRESOS FINANCIEROS:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 423, 343, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("GASTOS FINANCIEROS:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 455, 343, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("UTILIDAD ANTES DE IMPUESTOS:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 487, 343, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("IMPUESTO SOBRE LA RENTA:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 519, 343, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("RESERVA LEGAL:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 551, 343, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("UTILIDAD DEL EJERCICIO:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 577, 343, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 231, 18, 366));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, 20, 490));

        ventasNetas.setBackground(new java.awt.Color(0, 0, 0));
        ventasNetas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ventasNetas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventasNetas.setText(".");
        jPanel1.add(ventasNetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 231, 118, -1));

        costoVendido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        costoVendido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costoVendido.setText(".");
        jPanel1.add(costoVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 261, 118, -1));

        utilidadBruta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        utilidadBruta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        utilidadBruta.setText(".");
        jPanel1.add(utilidadBruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 293, 118, -1));

        gastosAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gastosAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gastosAdmin.setText(".");
        jPanel1.add(gastosAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 325, 118, -1));

        gastoVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gastoVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gastoVentas.setText(".");
        jPanel1.add(gastoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 357, 118, -1));

        utilidadOperacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        utilidadOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        utilidadOperacion.setText(".");
        jPanel1.add(utilidadOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 389, 118, -1));

        ingresosFinancieros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresosFinancieros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresosFinancieros.setText(".");
        jPanel1.add(ingresosFinancieros, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 421, 118, -1));

        gastosFinancieros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gastosFinancieros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gastosFinancieros.setText(".");
        jPanel1.add(gastosFinancieros, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 453, 118, -1));

        utilidadAntes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        utilidadAntes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        utilidadAntes.setText(".");
        jPanel1.add(utilidadAntes, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 485, 118, -1));

        isr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        isr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isr.setText(".");
        jPanel1.add(isr, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 517, 118, -1));

        reservaLegal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reservaLegal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservaLegal.setText(".");
        jPanel1.add(reservaLegal, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 549, 118, -1));

        utilidadEjercicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        utilidadEjercicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        utilidadEjercicio.setText(".");
        jPanel1.add(utilidadEjercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 577, 118, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("INVENTARIO FINAL:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 159, 30));

        inventariofinal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventariofinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inventariofinalKeyTyped(evt);
            }
        });
        jPanel1.add(inventariofinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 170, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 319, 63, 2));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 383, 63, 2));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 608, 63, 2));

        generar.setBackground(new java.awt.Color(0, 153, 51));
        generar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        generar.setForeground(new java.awt.Color(255, 255, 255));
        generar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        generar.setText("Generar");
        generar.setBorder(null);
        generar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 120, 40));

        reporte.setBackground(new java.awt.Color(102, 102, 255));
        reporte.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        reporte.setForeground(new java.awt.Color(255, 255, 255));
        reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        reporte.setText("Reporte");
        reporte.setBorder(null);
        reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 120, 40));

        salir.setBackground(new java.awt.Color(255, 0, 51));
        salir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("salir");
        salir.setBorder(null);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 670, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inventariofinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inventariofinalKeyTyped
        JTextField textField = (JTextField) evt.getSource();
        String textoActual = textField.getText();
        char c = evt.getKeyChar();

        // Permitir números, el punto decimal y retroceso
        if (!Character.isDigit(c) && c != '.' && c != '\b') {
            evt.consume(); // Ignorar cualquier carácter no válido
            return;
        }

        // Evitar múltiples puntos decimales
        if (c == '.' && textoActual.contains(".")) {
            evt.consume();
            return;
        }

        // Limitar a dos decimales
        if (textoActual.contains(".")) {
            int indexPunto = textoActual.indexOf('.');
            String decimales = textoActual.substring(indexPunto + 1);
            if (decimales.length() >= 2 && c != '\b') { // Permitir retroceso para corregir
                evt.consume();
            }
        }
    }//GEN-LAST:event_inventariofinalKeyTyped

    private boolean esFechaValida(String fecha) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false); // Validación estricta
        try {
            sdf.parse(fecha);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaEstadoResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaEstadoResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaEstadoResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaEstadoResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                VistaEstadoResultado dialog = new VistaEstadoResultado(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel costoVendido;
    public javax.swing.JLabel gastoVentas;
    public javax.swing.JLabel gastosAdmin;
    public javax.swing.JLabel gastosFinancieros;
    public javax.swing.JButton generar;
    public javax.swing.JLabel ingresosFinancieros;
    public javax.swing.JTextField inventariofinal;
    public javax.swing.JLabel isr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JButton reporte;
    public javax.swing.JLabel reservaLegal;
    public javax.swing.JButton salir;
    public javax.swing.JLabel utilidadAntes;
    public javax.swing.JLabel utilidadBruta;
    public javax.swing.JLabel utilidadEjercicio;
    public javax.swing.JLabel utilidadOperacion;
    public javax.swing.JLabel ventasNetas;
    // End of variables declaration//GEN-END:variables
}
